project:
  type: website
  output-dir: docs
  
website:
  title: "Deven Misra"
  favicon: /resources/tear.png
  navbar:
    logo: /resources/tear.png
    search: false
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
        
format:
  html:
    theme:
      light: dawn.scss
      dark: moon.scss
    css: styles.css
    toc: true
    email-obfuscation: references
