project:
  type: website
  output-dir: docs
  
website:
  title: "Deven Misra"
  favicon: /resources/tear.png
  navbar:
    logo: /resources/tear.png
    search: false
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
  page-footer: 
    center: <a href="https://www.u-tokyo.ac.jp/en/" style="text-decoration:none">UTokyo</a> $\vert$ <a href="https://www.ipmu.jp/en" style="text-decoration:none">Kavli IPMU</a> $\vert$ <a href="https://cd3.ipmu.jp" style="text-decoration:none">CD3</a>

format:
  html:
    theme: theme.scss
    css: styles.css
    toc: true
    email-obfuscation: references
