---
title: "Publications" 
subtitle: <a href="https://inspirehep.net/">INSPIRE-HEP {{< iconify academicons inspire >}}</a>
---

## Refereed Conference Publications
1. H. Wu, __D. Misra__ and G. S. Chirikjian, "<a href="https://ieeexplore.ieee.org/document/9197384" style="text-decoration: none">Is That a Chair? Imagining Affordances Using Simulations of an Articulated Human Body</a>," _2020 IEEE International Conference on Robotics and Automation (ICRA)_, Paris, France, 2020, pp. 7240-7246, doi: 10.1109/ICRA40945.2020.9197384.

## Conference Posters
1. __D. Misra__, O. Lee, H. Saberhagen, D. Schroeter and N. Charles, "Geometrically Disordered Network Models for the Integer Quantum Hall Transition via Loop Diagram Insertions," _2024 APS March Meeting_, Minneapolis, Minnesota, USA, 2024.

## Other Publications
1. __D. Misra__, "Multipole Moments of the Weyl-Lewis-Papapetrou Metric for an Axisymmetric Ring," Undergraduate Thesis, Dept. of Physics, Reed College, Portland, OR, 2022.

## Talks \& Presentations
1. "Low-Latency On-Chip $\tau$ Event Selection with Machine Learning for the Belle II Level-1 Trigger", Fast Machine Learning for Science Conference, ETH Zurich, September 2025. 
2. "Geometrically Disordered Network Models for the Integer Quantum Hall Transition", Workshop on the Physics and Mathematics of the Universe, Kavli IPMU, July 2025. 
3. "Low-Latency On-Chip $\tau$ Event Selection with Machine Learning for the Belle II Level-1 Trigger", ML4FE Workshop, University of Hawaii, May 2025. 
4. “Angle Reconstruction in High-Granularity Calorimeters with Graph Neural Networks”, SULI Research Symposium, Pacific Northwest National Laboratory, April 2023.
5. "Calorimeter Energy Reconstruction with Machine Learning", SULI Research Symposium, Pacific Northwest National Laboratory, December 2022.
6. "Axisymmetric Ring Sources in General Relativity", Physics Department Seminar, Reed College, May 2022.