---
title: "Research"
subtitle: <a href="https://orcid.org/0000-0003-3576-3414">ORCID {{< iconify academicons orcid >}}</a>
---
## Particle Physics
### <a href="https://www.belle2.org" style="text-decoration:none">Belle II</a>

I am currently a member of the Belle II collaboration affiliated with the <a href="https://www.ipmu.jp/en" style="text-decoration:none">Kavli Institute for the Physics and Mathematics of the Universe</a>. My research focuses on developing fast machine learning algorithms on FPGAs for the Belle II L1 trigger. 

___

### <a href="https://www.bnl.gov/eic/" style="text-decoration:none">Electron-Ion Collider</a>

Before joining Belle II, I worked on the development and implementation of advanced machine learning algorithms for energy and angle reconstruction in the Zero-Degree Calorimeter for the future Electron-Ion Collider. Data from simulations was used to perform the first angle reconstruction for hadronic showers in the far-forward calorimetry using a graph neural network. I also worked with the <a href="https://www.bnl.gov/eic/epic.php" style="text-decoration:none">ePIC</a> collaboration on refinement and validation of a new DD4hep-based framework for simulation studies.

## Condensed Matter Physics

### Quantum Phase Transitions
I am currently working with Professor <a href="https://www.reed.edu/physics/faculty/" style="text-decoration: none">Noah Charles</a> on a novel method of introducing geometric disorder to the Chalker-Coddington network model in order to accurately compute the critical exponent for the integer quantum hall transition. 

#### Related Publications
1. __D. Misra__, O. Lee, H. Saberhagen, D. Schroeter and N. Charles, "Geometrically Disordered Network Models for the Integer Quantum Hall Transition via Loop Diagram Insertions," _2024 APS March Meeting_, Minneapolis, Minnesota, USA, 2024.